name: MacOS.

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  prepare-libraries:
    name: Prepare Libraries
    runs-on: macos-latest

    strategy:
      matrix:
        defines:
          - ""
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"

    steps:
      - name: Clone.
        uses: actions/checkout@v7
        with:
          submodules: recursive
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
          path: ${{ env.REPO_NAME }}

      - name: First set up.
        run: |
          sudo chown -R `whoami`:admin /usr/local/share

          brew update
          brew upgrade || true
          brew install automake libtool meson nasm ninja pkg-config

          # Disable spotlight.
          sudo mdutil -a -i off

          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          sudo sed -i '' '/CMAKE_${lang}_FLAGS_DEBUG_INIT/s/ -g//' /opt/homebrew/share/cmake/Modules/Compiler/GNU.cmake

      - name: Restore libraries cache.
        id: cache-libs
        uses: actions/cache/restore@v6
        with:
          path: |
            Libraries
            ThirdParty
          key: ${{ runner.OS }}-libs-${{ hashFiles(format('{0}/{1}', env.REPO_NAME, env.PREPARE_PATH)) }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Libraries.
        id: build-libs
        run: |
          ./$REPO_NAME/Telegram/build/prepare/mac.sh skip-debug silent

      - name: Free up some disk space.
        run: find Libraries '(' '(' ! '(' -name '*.a' -o -name '*.h' -o -name '*.hpp' -o -name '*.inc' -o -name '*.cmake' -o -name '*.pc' -o -path '*/include/*' -o -path '*/objects-*' -o -path '*/cache_keys/*' -o -path '*/patches/*' -o -perm +111 ')' -type f ')' -o -empty ')' -delete

      - name: Save libraries cache.
        if: always() && steps.cache-libs.outcome == 'success' && steps.build-libs.outcome == 'success' && steps.cache-libs.outputs.cache-hit != 'true'
        uses: actions/cache/save@v6
        with:
          path: |
            Libraries
            ThirdParty
          key: ${{ steps.cache-libs.outputs.cache-primary-key }}

  build:
    name: MacOS
    runs-on: macos-latest
    needs: prepare-libraries
    permissions:
      contents: write

    strategy:
      matrix:
        arch: [arm64, x86_64]
        defines:
          - ""
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"

    steps:
      - name: Clone.
        uses: actions/checkout@v6
        with:
          submodules: recursive
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
          path: ${{ env.REPO_NAME }}

      - name: Restore libraries cache.
        id: cache-libs
        uses: actions/cache/restore@v5
        with:
          path: |
            Libraries
            ThirdParty
          key: ${{ runner.OS }}-libs-${{ hashFiles(format('{0}/{1}', env.REPO_NAME, env.PREPARE_PATH)) }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Configure.
        run: |
          cd $REPO_NAME/Telegram
          ./configure.sh \
          -D CMAKE_CONFIGURATION_TYPES=Release \
          -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO \
          -D TDESKTOP_API_ID=${{ secrets.API_ID }} \
          -D TDESKTOP_API_HASH=${{ secrets.API_HASH }} \
          -D DESKTOP_APP_MAC_ARCH=${{ matrix.arch }} \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=OFF \
          -D CMAKE_EXE_LINKER_FLAGS="-Wl,-x"

      - name: Telegram Desktop build.
        if: env.ONLY_CACHE == 'false'
        run: |
          cd $REPO_NAME/Telegram
          cmake --build ../out --config Release --parallel

      - name: Move artifact.
        id: prepare-artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          cd $REPO_NAME
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
          else
            VERSION="v$(grep 'AppVersionStr' Telegram/SourceFiles/core/version.h | cut -d '"' -f 2)"
          fi
          cd out/Release
          mkdir artifact
          mv Yurigram.app artifact/
          mv Updater artifact/
          if [ "${{ matrix.arch }}" == "arm64" ]; then
          	PLATFORM="AppleSilicon"
          else
            PLATFORM="Intel"
          fi
          echo "name=Yurigram_MacOS_${VERSION}_${PLATFORM}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v7
        if: env.UPLOAD_ARTIFACT == 'true'
        name: Upload artifact.
        with:
          name: ${{ steps.prepare-artifact.outputs.name }}
          path: ${{ env.REPO_NAME }}/out/Release/artifact/

      - name: Package release artifact.
        id: package-release
        if: github.event_name == 'release' && env.UPLOAD_ARTIFACT == 'true'
        run: |
          ARCHIVE="$REPO_NAME/out/Release/${{ steps.prepare-artifact.outputs.name }}.zip"
          (
            cd "$REPO_NAME/out/Release/artifact"
            zip -r -y "../${{ steps.prepare-artifact.outputs.name }}.zip" Yurigram.app Updater
          )
          echo "archive=$ARCHIVE" >> "$GITHUB_OUTPUT"

      - name: Upload release package.
        if: github.event_name == 'release' && env.UPLOAD_ARTIFACT == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ github.event.release.id }}
          file: ${{ steps.package-release.outputs.archive }}